name: Upload MEI files to TU-RDM

on:
  workflow_call:
    # secrets:
    #     RDM_TEST_API_TOKEN_JJ:
    #         required: false


jobs:
  run-shared-script:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout caller repository
      - name: Checkout caller repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
          path: caller-repo

      # 2. Checkout shared repository (this repo)
      - name: Checkout shared repository
        uses: actions/checkout@v4
        with:
          repository: e-laute/E-LAUTE_GH_Actions
          ref: main
          path: shared-actions

      # 3. Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      # 4. Install dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          # pip install -r shared-actions/scripts/requirements.txt
          pip install requests lxml pandas

      # 5. Run the shared script *on the caller repo*
      - name: Run upload_mei.py script to upload all mei-files in the repository
        run: |
          export RDM_TEST_API_TOKEN_JJ="${{secrets.RDM_TEST_API_TOKEN_JJ}}"
          python -m scripts/upload_to_RDM.upload_meis --draft-one
        # python -m scripts/upload_to_RDM.upload_meis
